language: c

matrix:
  include:
    - os: linux
      name: "linux gcc"
      compiler: gcc

    - os: linux
      name: "linux gcc-4.9"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: linux
      name: "linux gcc-5"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      name: "linux gcc-6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      name: "linux gcc-7"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: osx
      name: "osx gcc-4.9"
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: osx
      name: "osx clang"
      compiler: clang
      env:
        - MATRIX_EVAL=""

    - os: linux
      name: "linux clang"
      compiler: clang
      env:
        - MATRIX_EVAL=""



before_install:
    - eval "${MATRIX_EVAL}"
    - ${CC} --version

script:
  - ./build.sh
